package com.example.carserviceapp

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class DBHelper(context: Context) : SQLiteOpenHelper(context, "CARSERVICEDB", null, 1) {
    override fun onCreate(db: SQLiteDatabase?) {
        db?.execSQL("CREATE TABLE CUSTOMER(CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME TEXT, FAMILY_NAME TEXT, GENDER TEXT, REGION TEXT, CITY TEXT, MOBILE_PHONE INTEGER, NATIONAL_ID INTEGER, DOB TEXT, EMAIL TEXT, PASSWORD TEXT)")
        db?.execSQL("CREATE TABLE ADMIN(ADMIN_ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME TEXT, FAMILY_NAME TEXT, GENDER TEXT, REGION TEXT, CITY TEXT, MOBILE_PHONE INTEGER, NATIONAL_ID INTEGER, EMAIL TEXT, PASSWORD TEXT, ADMIN_TYPE TEXT)")
        db?.execSQL("CREATE TABLE CAR_INFO(CAR_INFO_ID INTEGER PRIMARY KEY AUTOINCREMENT, CAR_PLATE_NUMBER TEXT, CAR_REGISTRATION_NUMBER TEXT, BRAND TEXT, MODEL TEXT, YEAR INTEGER)")
        db?.execSQL("CREATE TABLE CUSTOMER_CARS(CUSTOMER_CAR_ID INTEGER PRIMARY KEY AUTOINCREMENT, CUSTOMER_ID INTEGER, CAR_PLATE_NUMBER INTEGER, CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID), CONSTRAINT FK_CAR_PLATE_NUMBER FOREIGN KEY(CAR_PLATE_NUMBER) REFERENCES CAR_INFO(CAR_PLATE_NUMBER))")
        db?.execSQL("CREATE TABLE APPOINTMENTS(APPOINTMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT, CAR_PLATE_NUMBER INTEGER, CUSTOMER_ID INTEGER, DATE_TIME TEXT, SERVICE_REASON TEXT, CONSTRAINT FK_CAR_PLATE_NUMBER FOREIGN KEY(CAR_PLATE_NUMBER) REFERENCES CAR_INFO(CAR_PLATE_NUMBER), CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID))")
        db?.execSQL("CREATE TABLE MECHANIC_WORK(MECHANIC_WORK_ID INTEGER PRIMARY KEY AUTOINCREMENT, ADMIN_ID INTEGER, CAR_PLATE_NUMBER INTEGER, CONSTRAINT FK_ADMIN_ID FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID), CONSTRAINT FK_CAR_PLATE_NUMBER FOREIGN KEY(CAR_PLATE_NUMBER) REFERENCES CAR_INFO(CAR_PLATE_NUMBER))")
        db?.execSQL("CREATE TABLE SERVICES(SERVICE_ID INTEGER PRIMARY KEY AUTOINCREMENT, SERVICE_NAME TEXT, SERVICE_PRICE INTEGER)")
        db?.execSQL("CREATE TABLE TRACK_CAR(TRACK_CAR_ID INTEGER PRIMARY KEY AUTOINCREMENT, CAR_PLATE_NUMBER INTEGER, STATUS TEXT, CURRENT_MILLAGE INTEGER, PROBLEMS TEXT, ADDITIONAL_COMMENTS TEXT, CONSTRAINT FK_CAR_PLATE_NUMBER FOREIGN KEY(CAR_PLATE_NUMBER) REFERENCES CAR_INFO(CAR_PLATE_NUMBER))")
        db?.execSQL("CREATE TABLE SERVICES_DONE(SERVICE_DONE_ID INTEGER PRIMARY KEY AUTOINCREMENT, TRACK_CAR_ID INTEGER, MECHANIC_ID INTEGER, SERVICE_ID INTEGER, CONSTRAINT FK_TRACK_CAR_ID FOREIGN KEY(TRACK_CAR_ID) REFERENCES TRACK_CAR(TRACK_CAR_ID), CONSTRAINT FK_MECHANIC_ID FOREIGN KEY(MECHANIC_ID) REFERENCES MECHANIC_WORK(MECHANIC_ID),  CONSTRAINT FK_SERVICE_ID FOREIGN KEY(SERVICE_ID) REFERENCES SERVICES(SERVICE_ID))")





        //PrePopulating Data
        db?.execSQL("INSERT INTO ADMIN(FIRST_NAME, FAMILY_NAME, GENDER, REGION, CITY, MOBILE_PHONE, NATIONAL_ID, EMAIL, PASSWORD, ADMIN_TYPE) VALUES ('Mohammad','Gerashi','Male','Qatar','Doha','70079955','43678643','mg@me.com','NqbV4paEdH2HpmxVrPefXg==','Mechanic')")

        db?.execSQL("INSERT INTO CUSTOMER(FIRST_NAME, FAMILY_NAME, GENDER, REGION, CITY, MOBILE_PHONE, NATIONAL_ID, DOB, EMAIL, PASSWORD) VALUES ('Bob', 'John', 'Male', 'Qatar', 'Doha', '44444444', '444434674', '12/22/1995', 'bob@bob.com', 'NqbV4paEdH2HpmxVrPefXg==')")

        db?.execSQL("INSERT INTO SERVICES(SERVICE_NAME, SERVICE_PRICE) VALUES ('Oil', '150')")
        db?.execSQL("INSERT INTO SERVICES(SERVICE_NAME, SERVICE_PRICE) VALUES ('Air Filter', '100')")
        db?.execSQL("INSERT INTO SERVICES(SERVICE_NAME, SERVICE_PRICE) VALUES ('Fuel Filter', '250')")
        db?.execSQL("INSERT INTO SERVICES(SERVICE_NAME, SERVICE_PRICE) VALUES ('Battery', '550')")
        db?.execSQL("INSERT INTO SERVICES(SERVICE_NAME, SERVICE_PRICE) VALUES ('Radiator Liquid', '100')")
        db?.execSQL("INSERT INTO SERVICES(SERVICE_NAME, SERVICE_PRICE) VALUES ('Rear Brake Pads', '250')")
        db?.execSQL("INSERT INTO SERVICES(SERVICE_NAME, SERVICE_PRICE) VALUES ('Front Break Pads', '250')")
        db?.execSQL("INSERT INTO SERVICES(SERVICE_NAME, SERVICE_PRICE) VALUES ('Engine Flush', '350')")


        db?.execSQL("INSERT INTO CAR_INFO(CAR_PLATE_NUMBER, CAR_REGISTRATION_NUMBER, BRAND, MODEL, YEAR) VALUES ('787411', '4563293949565', 'Toyota', 'Land Cruiser', '2019')")

        db?.execSQL("INSERT INTO CAR_INFO(CAR_PLATE_NUMBER, CAR_REGISTRATION_NUMBER, BRAND, MODEL, YEAR) VALUES ('345476', '4587698765876', 'Lexus', 'LX570', '2020')")

        db?.execSQL("INSERT INTO CAR_INFO(CAR_PLATE_NUMBER, CAR_REGISTRATION_NUMBER, BRAND, MODEL, YEAR) VALUES ('867555', '8762352876987', 'Toyota', 'FJ', '2014')")

        db?.execSQL("INSERT INTO CUSTOMER_CARS(CUSTOMER_ID, CAR_INFO_ID) VALUES (1,1)")
        db?.execSQL("INSERT INTO CUSTOMER_CARS(CUSTOMER_ID, CAR_INFO_ID) VALUES (1,2)")
        db?.execSQL("INSERT INTO CUSTOMER_CARS(CUSTOMER_ID, CAR_INFO_ID) VALUES (1,3)")

        db?.execSQL("INSERT INTO MECHANIC_WORK(ADMIN_ID, CAR_INFO_ID) VALUES (1,2)")

        db?.execSQL("INSERT INTO TRACK_CAR(CAR_INFO_ID, STATUS, CURRENT_MILLAGE, PROBLEMS, ADDITONAL_COMMENT) VALUES (1,'Working On','14000', 'No problems' 'N/A')")

        db?.execSQL("INSERT INTO SERVICES_DONE(TRACK_CAR_ID, MECHANIC_WORK_ID, SERVICE_ID) VALUES (1,1,1)")
        db?.execSQL("INSERT INTO SERVICES_DONE(TRACK_CAR_ID, MECHANIC_WORK_ID, SERVICE_ID) VALUES (1,1,2)")
        db?.execSQL("INSERT INTO SERVICES_DONE(TRACK_CAR_ID, MECHANIC_WORK_ID, SERVICE_ID) VALUES (1,1,5)")
    }

    override fun onUpgrade(p0: SQLiteDatabase?, p1: Int, p2: Int) {

    }
}